README.md

The claim about gokrazy and p9 is not yet true. Needs #5 and fixing one other bug: global name collisions.

README: explain gobusybox

---

.circleci/config.yml

bazel is taking 15 minutes to build and test everything on circleci: https://app.circleci.com/pipelines/github/u-root/gobusybox/178/workflows/6709863c-d97b-478c-9914-c2f82a786262
That's crazy. Let's see if batching them allows for more bazel caching... otherwise, I'll split them into separate containers that can run in parallel.

circleci: optimize bazel runtime

---

README.md

This is not actually a problem -- the resulting binary will just use
both different dependencies.

README: drop major version conflict

---

gobuilds.sh
src/pkg/bb/bbinternal/bb.go
test/12-fancy-cmd/go.mod
test/12-fancy-cmd/main.go
test/12-fancy-cmd/test.sh

fix command names being invalid package names

---

src/pkg/bb/BUILD.bazel
src/pkg/bb/bb.go
src/pkg/bb/bbinternal/BUILD.bazel
src/pkg/bb/bbinternal/bb.go
src/pkg/bb/findpkg/BUILD.bazel
src/pkg/bb/findpkg/bb.go
src/pkg/bb/findpkg/bb_test.go

part 1: bbinternal remains the stuff shared between bazel and standard
Go, the stuff that modifies AST, parses & writes Go files, and creates a
main.go.
part 2: findpkg turns a list of user-input package names/globs into
Packages we know.
Signed-off-by: Chris Koch <chrisko@google.com>

Split bbinternal package

---

.circleci/config.yml
README.md
WORKSPACE
src/pkg/bb/bb.go
test-external.sh
test-multi-simple.sh
test/nested/cmd/strace/strace.go
vendortest/cmd/strace/strace.go

This fixes Go module gobusybox builds across multiple modules, i.e. if you're building commands from e.g. both u-root and u-bmc.

Fix failing Go module builds

---

src/cmd/makebb/makebb.go
src/pkg/bb/bb.go

-g will allow the package to generate code but not compile it.
Systems like tamago are not quite in reach for makebb to build just yet.
Signed-off-by: Ronald G. Minnich <rminnich@gmail.com>

makebb: and a generate code but do not build switch

---

src/pkg/bb/bb.go

This desperately needs some tests too.
before:
```
./u-root -defaultsh="" ./cmds/core/ip ./cmds/core/init ~/cpu/cmds/cpu
2021/12/29 21:33:30 Disabling CGO for u-root...
2021/12/29 21:33:30 Build environment: GOARCH=amd64 GOOS=linux GOROOT=/usr/lib/google-golang GOPATH=/usr/local/google/home/chrisko/go CGO_ENABLED=0
2021/12/29 21:33:30 NOTE: building with the new gobusybox; to get old behavior, use -build=bb
2021/12/29 21:33:32 Conflicting module dependencies on github.com/u-root/u-root:
2021/12/29 21:33:32   github.com/u-root/cpu uses version v0.8.0
2021/12/29 21:33:32   your request to compile github.com/u-root/u-root from /usr/local/google/home/chrisko/go/src/github.com/u-root/u-root uses version 
2021/12/29 21:33:32 Suggestion to resolve: add `replace github.com/u-root/u-root => …
```

bb: don't print module conflict error duplicates

---

README.md

Depending on two different major versions of dhcp is actually not a
conflict.

README: fix small typo

---

src/pkg/bb/bb.go

For
```
$ ./u-root -defaultsh="" ./cmds/core/ip ./cmds/core/init ~/cpu/cmds/cpu
```
Before:
```
13:37:03 Conflicting module dependencies on github.com/u-root/u-root:
13:37:03   module github.com/u-root/cpu depends on github.com/u-root/u-root @ version v0.8.0
13:37:03   your request to compile github.com/u-root/u-root/cmds/core/ip depends on github.com/u-root/u-root @ directory /usr/local/google/home/chrisko/go/src/github.com/u-root/u-root
```
After:
```
13:37:03 Conflicting module dependencies on github.com/u-root/u-root:
13:37:03   github.com/u-root/cpu/cmds/cpu depends on github.com/u-root/u-root @ version v0.8.0
13:37:03   github.com/u-root/u-root/cmds/core/ip depends on github.com/u-root/u-root @ directory /usr/local/google/home/chrisko/go/src/github.com/u-root/u-root
```

bb: clearer origin of dependency conflicts

---

.circleci/config.yml

Doesn't fix any of the things mentioned in #64 -- just makes sure that all the existing features work with Go 1.18.

Ensure no regressions with Go 1.18

---

src/pkg/monoimporter/monoimporter.go

When a command imported both package "errors" and
"golang.org/x/crypto/errors", the "errors" package was matched to the
crypto one erroneously. Fix the import order.

monoimporter: fix package import attempt order

---

src/cmd/rewritepkg/main.go
src/pkg/bb/bbinternal/bb.go

Instead of copying the existing file and betting that bazel/blaze will
exclude them based on their build tag, we write out a near-empty file
(with just a package declaration) instead.
This way the destination directory only contains files with `package
<rewritten-package-name>`, rather than a mix of `package
<rewritten-package-name>` and `package main`.

bazel: write out empty files for files excluded by build tag

---

README.md
src/pkg/bb/bb.go
test/requestconflict/test.sh

if any third-party cmd we pull in to build uses u-root as a dependency,
it will always conflict. When building u-root, u-root is always pulled
in as a local dependency i.e. github.com/u-root/u-root@directory. This
conflicts with every go.mod that is outside of u-root/u-root and depends
on u-root.
Signed-off-by: Christian Walter <christian.walter@9elements.com>

src/pkg/bb: Resolve conflicting u-root

---

src/pkg/bb/findpkg/bb.go

loadFSPackages is currently ignoring errors returned by addPkg.
This results in a very bad outcome: firmware images that are missing commands.
For example, if you corrupt, e.g., date, u-root will still build
a firmware image with date missing.
This has, in turn, resulted in the creation of broken images (found in
the wild for those of us using cpu).
There is now a test in u-root specifically for the case that
this error is ignored (https://github.com/u-root/u-root/pull/2451)
and this fix makes that new test work, where it does not pass
currently.
Signed-off-by: Ronald G. Minnich <rminnich@gmail.com>

loadFSPackages: do not ignore errors from addPkg

---

README.md

Signed-off-by: Daniel Maslowski <info@orangecms.org>

README: fix up command names in how it works section

---

src/pkg/bb/bbinternal/bb.go

Fix panic in the case where one of the dependencies of the commands has a build error. In that case, WritePkg p.GoFiles[0] access will fail.

Fix panic writing dependency packages

---

src/pkg/bb/findpkg/bb.go

If a user sets, e.g., -tags tinygo, that tag must be used in the loadPkgs step, as well as the build step, else directories will be populated with files that can not be used.
Example: if we run
u-root -tags tinygo
files are copied to the build directory that should not be, and build steps will get an error.
With this change, tags will control both the file copy step as well as the build step.
Signed-off-by: Ronald G. Minnich <rminnich@google.com>

use BuildTags in find package step

---

src/pkg/bb/bb.go
src/pkg/bb/findpkg/bb.go
src/pkg/bb/findpkg/bb_test.go
src/pkg/golang/build.go

Instead of the clunky
env := golang.Default()
env.CgoEnabled = false
env.GOARCH = ...
Then using &env somewhere like in u-root, we now have a nicer With* API that should allow all this in one line:
env := golang.Default(golang.DisableCGO(), golang.WithGOARCH("arm"))

API: improve golang.Default

---

gobuilds-gopath.sh
src/pkg/bb/findpkg/bb.go
src/pkg/golang/BUILD.bazel
src/pkg/golang/build.go

Make sure that build tags are provided in every call to packages.Load by providing one common API, also usable by external callers.

golang: provide common packages.Load API

---

src/pkg/golang/build.go

The default mode is on, e.g. when GO111MODULE is empty.

Use -mod=readonly in all cases where GO111MODULE=on

---

README.md
src/cmd/gencmddeps/.gitignore
src/cmd/gencmddeps/main.go
src/go.mod
src/go.sum
src/pkg/bb/findpkg/bb.go
src/pkg/bb/findpkg/bb_test.go

Users of the `pkg/bb` API may now specify shell expansions such as `github.com/u-root/u-root/cmds/core/{init,ip}`, and they will be expanded by mvdan.cc/sh's field expansion from https://pkg.go.dev/mvdan.cc/sh/v3@v3.8.0/shell#Fields (without expanding environment variables).
This will be useful in mkuimage templates.

Support shell expansion in API & gencmddeps tool

---

src/cmd/makebb/makebb.go
src/pkg/golang/build.go
src/pkg/golang/compiler.go

help: 
- ~~I haven't figured out how to propagate this to mkuimage.~~
- it may make more sense as a buildopt instead of environ in build.go(?)
- but the BuildOpts isn't always available
- name of flag? -go-compiler(?)
- any feedback! 
This allows specifying the compiler explicitly in makebb and handles peculiarities of tinygo.  It works by resolving and caching the path to the go-compiler then queries tinygo for its hidden go-build-tags and propagates them to package lookup / install. This allows the pruning algorithm to correctly add / remove files when syncing dependent packages.
Usage:
```
% makebb -h 
Usage of makebb:
-compiler string
override go compiler to use (e.g. "/path/to/tinygo")
[...]
```
Resulting busybox is significantly smaller.  I compiled a slightly more complicated …

tinygo: -compiler command line argument (e.g. tinygo)

---

src/pkg/golang/compiler.go
src/pkg/golang/compiler_test.go

External code such as u-root depend on its existence.
Done this way in case someone wants to further change things.

Restore GoCmd for Environ
